- name: install impulse xdr manager
  hosts: impulse_agents
  tasks:
    - name: download agent tarball
      become: yes
      command: sudo wget -O /opt/agent-{{ asset }}.tar.gz https://{{ manager_ip }}:7001/api/enroll --post-data "secret_key={{ preshare }}" --no-check-certificate 

    - name: untar the package in /opt
      become: yes
      command: sudo tar xf /opt/agent-{{ asset }}.tar.gz
      args:
        chdir: /opt 
    
    - name: install impulse xdr agent (~3 minutes)
      become: yes
      command: sudo ./install_agent.sh
      args:
        chdir: /opt/impulse