- name: vyos network config
  hosts: vyos
  vars_prompt:

  - name: password
    prompt: Enter your new vyos password
    private: true
  tasks:
    - name: Set the password hash fact
      set_fact:
        password_hash: "{{ password | password_hash('sha512') }}"
    - name: load vyos config from template
      become: yes
      template:
        src: config.boot.j2
        dest: /config/config.boot
        mode: "0775"
        owner: root
        group: vyattacfg
    - name: bounce and end
      become: yes
      shell: nohup bash -c "/usr/bin/sleep 10 && /usr/sbin/shutdown -r now" &